import 'src/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/components/Header/Header';
import { Mantine } from '@/components/Providers';
import { isAuth } from '@/shared/utils/isAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const isUserAuth = await isAuth();

  return (
    <html lang="en">
      <Mantine>
        <body className={inter.className}>
          {isUserAuth && <Header />}

          {children}
        </body>
      </Mantine>
    </html>
  );
}
